name: qlickcare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  salomon_bottom_bar: ^3.3.2
  image_picker: ^1.2.1
  font_awesome_flutter: ^10.12.0
  jwt_decoder: ^2.0.1
  lottie: ^3.3.2
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  permission_handler: ^12.0.1
  cached_network_image: ^3.4.1
  device_info_plus: ^12.3.0
  flutter_local_notifications: ^17.1.2
  geocoding: ^4.0.0
  slide_to_act: ^2.0.2
  open_filex: ^4.7.0
  change_app_package_name: ^1.5.0
  intl: ^0.20.2
  web_socket_channel: ^3.0.3
  file_picker: ^10.3.8
  mime: ^2.0.0
  flutter_webrtc: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/loading.json
    - assets/images/logo.png
    - assets/images/on1.png
    - assets/images/on2.png
    - assets/images/on3.png
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/applogo.png
  android_icon_name: ic_launcher
  ios_icon_name: AppIcon